[workspace]
resolver = "2"
members = [
    "meilisearch",
    "meilisearch-types",
    "meilisearch-auth",
    "meili-snap",
    "index-scheduler",
    "dump",
    "file-store",
    "permissive-json-pointer",
]

[profile.release]
codegen-units = 1

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.milli]
opt-level = 3
